services:
  - type: web
    name: ssocio-pro-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: CLIENT_ORIGIN
        value: https://ritvik78.github.io
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false