create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  audience text not null check (audience in ('brand', 'influencer')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists submissions_audience_created_at_idx
  on public.submissions (audience, created_at);

alter table public.submissions enable row level security;

drop policy if exists "Public can read submissions" on public.submissions;
create policy "Public can read submissions"
  on public.submissions for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can insert submissions" on public.submissions;
create policy "Public can insert submissions"
  on public.submissions for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Public can delete submissions" on public.submissions;
create policy "Public can delete submissions"
  on public.submissions for delete
  to anon, authenticated
  using (true);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null default 'Ops / Admin' check (role in ('Ops / Admin', 'Brand', 'Influencer')),
  token_hash text,
  created_at timestamptz not null default now()
);

create index if not exists users_username_idx
  on public.users (username);

-- Accounts are created, verified, and signed in only through the backend API
-- (service role), so this table intentionally has no public policies.
