create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  audience text not null check (audience in ('brand', 'influencer')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists submissions_audience_created_at_idx
  on public.submissions (audience, created_at);

alter table public.submissions enable row level security;

drop policy if exists "Public can read submissions" on public.submissions;
create policy "Public can read submissions"
  on public.submissions for select
  to anon, authenticated
  using (true);

drop policy if exists "Public can insert submissions" on public.submissions;
create policy "Public can insert submissions"
  on public.submissions for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Public can delete submissions" on public.submissions;
create policy "Public can delete submissions"
  on public.submissions for delete
  to anon, authenticated
  using (true);

-- Supabase Auth seeds the fixed admin account for the demo portal.
--
-- Credentials live in auth.users (Supabase's managed auth) and are created
-- directly by the GoTrue service through the standard sign-up flow, then the
-- account is confirmed here. This is the only SQL touch point: manual rows
-- must mirror GoTrue exactly (bcrypt cost 10, user_metadata containing
-- sub/email/email_verified/phone_verified, identity row present, and all
-- token columns as empty strings '' rather than NULL, otherwise login fails
-- with "Database error querying schema").
--
-- The public.users table kept by earlier migrations is no longer used.
delete from auth.identities where email = 'admin@gmail.com';
delete from auth.users where email = 'admin@gmail.com';

with new_id as (select gen_random_uuid() as uid)
, new_user as (
  insert into auth.users (
    instance_id, id, aud, role, email,
    encrypted_password,
    email_confirmed_at, created_at, updated_at,
    raw_app_meta_data, raw_user_meta_data,
    confirmation_token, recovery_token,
    email_change_token_new, email_change,
    phone_change, phone_change_token,
    email_change_token_current, reauthentication_token
  ) select
    '00000000-0000-0000-0000-000000000000',
    uid,
    'authenticated', 'authenticated',
    'admin@gmail.com',
    crypt('admin@123', gen_salt('bf', 10)),
    now(), now(), now(),
    '{"provider":"email","providers":["email"]}',
    jsonb_build_object(
      'sub', uid::text,
      'email', 'admin@gmail.com',
      'email_verified', true,
      'phone_verified', false,
      'name', 'Admin',
      'role', 'Ops / Admin'
    ),
    '', '', '', '', '', '', '', ''
  from new_id
  returning id
) insert into auth.identities (
  id, provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at
) select
  gen_random_uuid(), uid, uid,
  jsonb_build_object(
    'sub', uid::text,
    'email', 'admin@gmail.com',
    'email_verified', true,
    'phone_verified', false
  ),
  'email', now(), now(), now()
from new_id;