create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  audience text not null check (audience in ('brand', 'influencer')),
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists submissions_audience_created_at_idx
  on public.submissions (audience, created_at);

alter table public.submissions enable row level security;

create policy "Public can read submissions"
  on public.submissions for select
  to anon, authenticated
  using (true);

create policy "Public can insert submissions"
  on public.submissions for insert
  to anon, authenticated
  with check (true);

create policy "Public can delete submissions"
  on public.submissions for delete
  to anon, authenticated
  using (true);
